### ISSUE TITLE
Still unable to run idevicerestore on Iphone 6

### ISSUE THREAD

**Issue by TheNegativeZero** [libimobiledevice/idevicerestore#338]
Hi guys, after a few days banging my head against a brick wall, "idevicerestore -l" ends on the infamous "Unable to receive message from FDR 0x55b0cfdc1f10 (-2). 0/2 bytes" error.  I modified fdr.c to allow for more retries to open the port and set a longer SLEEP wait but to no avail.

On the other hand, irecovery reports accurately when I am in either RESTORE or DFU mode.  I am able to set the iPhone 6 (A1586) to either state and even send commands thru irecovery.  When in idevicerestore, the program(s) run without any hicups until I hit the aforementioned error.

Questions:
(1). Is there a way to push the iPhone firmware thru an irecovery command (-s).
(2). Is the latest compile of idevicerestore ok?  I am also compiling libplist, libusbmuxd, libimobiledevice, usbmuxd, libirecovery, and of course idevicerestore.  All compiles finish ok just with a few warnings about unused variables.
(3), Is there any procedure to run this that I am missing?

Many thanks in advance.

**Comment by nikias** [comment]
No, you can't push fw through irecovery.
`"Unable to receive message from FDR 0x55b0cfdc1f10 (-2). 0/2 bytes"` isn't the reason why it fails. I recently restored an iPhone X with the latest codebase and got a lot of those messages but it still restored fine.
What platform are you on? Any more log output? With -d ?

**Comment by TheNegativeZero** [comment]
Thanks for your kind and prompt response Nikias.  The problem is that because I have my iPhone6 stuck in a boot loop, I wanted to make it bootable again.  I read that idevicerestore would clear this condition by reinstalling the .ipsw file and all required files.

Im working on Ubuntu 20.04 but have access to Win10 and MacOS if needed.  I donty want to downgrade or jailbrake the phone, just want to make it bootable again.

Many thanks again in advance.  Your help is much appreciated.

idevicerestore -l -d

irecv_event_cb: device 00162c543831a826 (udid: N/A) connected in Recovery mode
Found device in Recovery mode
opening device 05ac:1281...
found device with ECID 00162c543831a826
Setting to configuration 1
Setting to interface 0:0
Identified device as n61ap, iPhone7,2
*   Trying 172.67.83.193:443...
* TCP_NODELAY set
* Connected to api.ipsw.me (172.67.83.193) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Mar 19 00:00:00 2020 GMT
*  expire date: Oct  9 12:00:00 2020 GMT
*  subjectAltName: host "api.ipsw.me" matched cert's "*.ipsw.me"
*  issuer: C=US; ST=CA; L=San Francisco; O=CloudFlare, Inc.; CN=CloudFlare Inc ECC CA-2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x561a4ac75890)
> GET /v3/device/iPhone7,2 HTTP/2
Host: api.ipsw.me
user-agent: InetURL/1.0 idevicerestore/1.0
accept: */*

* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Wed, 03 Jun 2020 03:04:13 GMT
< content-type: application/json
< set-cookie: __cfduid=dbf3f0e5b1011a056e175e342029780bc1591153452; expires=Fri, 03-Jul-20 03:04:12 GMT; path=/; domain=.ipsw.me; HttpOnly; SameSite=Lax; Secure
< vary: Accept-Encoding
< access-control-allow-origin: *
< access-control-expose-headers: X-Data-Location, X-Server-Location
< cache-control: public
< content-md5: 45Lg4mLuDqZ3ZCyLgR/lxA==
< content-security-policy: default-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none'
< expires: Wed, 03 Jun 2020 03:33:00 GMT
< vary: Origin
< x-content-type-options: nosniff
< x-data-location: cache
< x-frame-options: DENY
< x-server-location: 11e1a48cc0a2
< x-xss-protection: 1; mode=block
< strict-transport-security: max-age=15552000; preload
< x-frame-options: DENY
< cf-cache-status: EXPIRED
< cf-request-id: 0319bbfeab0000dec7f0b93200000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 59d62f777cb7dec7-GUA
< alt-svc: h3-27=":443"; ma=86400
< 
* Connection #0 to host api.ipsw.me left intact
The following firmwares are currently being signed for iPhone7,2:
  [1] 12.4.7 (build 16G192)
Select the firmware you want to restore: 1
Selected firmware 12.4.7 (build 16G192)
ERROR: could not open or create lockfile 'iPhone_4.7_12.4.7_16G192_Restore.ipsw.lock'
WARNING: Could not lock file 'iPhone_4.7_12.4.7_16G192_Restore.ipsw.lock'
Verifying 'iPhone_4.7_12.4.7_16G192_Restore.ipsw'...
Checksum matches.
WARNING: Could not unlock file 'iPhone_4.7_12.4.7_16G192_Restore.ipsw.lock'
Extracting BuildManifest from IPSW
Product Version: 12.4.7
Product Build: 16G192 Major: 16
opening device 05ac:1281...
found device with ECID 00162c543831a826
Setting to configuration 1
Setting to interface 0:0
INFO: device serial number is C37P6RH5G5MV
Device supports Image4: true
Variant: Customer Upgrade Install (IPSW)
This restore will update your device without erasing user data.
Checking IPSW for required components...
All required components found in IPSW
Using cached filesystem from 'iPhone_4.7_12.4.7_16G192_Restore/038-53521-004.dmg'
Getting device's ECID for TSS request
Found ECID 6241189719287846
Getting ApNonce in recovery mode... 5e 36 31 ab 2b 26 44 85 9e 06 9d a3 7d 92 8c 73 01 15 e1 44 
Trying to fetch new SHSH blob
Getting SepNonce in recovery mode... 59 33 92 13 5a bf 57 22 d3 63 a9 68 9d 4d 7f 23 26 56 ee 33 
NOTE: Unable to find BbCalibrationManifestKeyHash node
NOTE: Unable to find BbFactoryActivationManifestKeyHash node
NOTE: Unable to find BbSkeyId node
DEBUG: Applying restore request rules for entry AppleLogo
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry BatteryCharging0
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry BatteryCharging1
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry BatteryFull
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry BatteryLow0
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry BatteryLow1
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry BatteryPlugin
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry DeviceTree
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry KernelCache
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry LLB
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry OS
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry RecoveryMode
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry RestoreDeviceTree
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry RestoreKernelCache
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry RestoreLogo
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry RestoreRamDisk
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry RestoreSEP
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Applying restore request rules for entry RestoreTrustCache
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry SEP
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Applying restore request rules for entry StaticTrustCache
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry ftap
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: No Digest data, using empty value for entry ftap
DEBUG: Applying restore request rules for entry ftsp
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Adding EPRO=true to TSS entry
DEBUG: No Digest data, using empty value for entry ftsp
DEBUG: Applying restore request rules for entry iBEC
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry iBSS
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry iBoot
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Applying restore request rules for entry rfta
DEBUG: Adding EPRO=true to TSS entry
DEBUG: Adding ESEC=true to TSS entry
DEBUG: No Digest data, using empty value for entry rfta
DEBUG: Applying restore request rules for entry rfts
DEBUG: Adding ESEC=true to TSS entry
DEBUG: Adding EPRO=true to TSS entry
DEBUG: No Digest data, using empty value for entry rfts
common.c:printing 6320 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>@Locality</key>
	<string>en_US</string>
	<key>@HostPlatformInfo</key>
	<string>mac</string>
	<key>@VersionInfo</key>
	<string>libauthinstall-698.0.5</string>
	<key>@UUID</key>
	<string>195AB6E0-A01E-0842-DA65-BB2268575D1C</string>
	<key>ApECID</key>
	<integer>6241189719287846</integer>
	<key>UniqueBuildID</key>
	<data>
	9+VDTJD7agKLDpaYYh5pxMl00+Y=
	</data>
	<key>ApChipID</key>
	<integer>28672</integer>
	<key>ApBoardID</key>
	<integer>6</integer>
	<key>ApSecurityDomain</key>
	<integer>1</integer>
	<key>AppleLogo</key>
	<dict>
		<key>Digest</key>
		<data>
		lKWyBoS/W2XT5kKt+BANOauEuvw=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>BatteryCharging0</key>
	<dict>
		<key>Digest</key>
		<data>
		tq8prikOt2WTaP7W27DVEA0KQ38=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>BatteryCharging1</key>
	<dict>
		<key>Digest</key>
		<data>
		NbatNhLbMJ+JUUbBjLC9Jow7cNI=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>BatteryFull</key>
	<dict>
		<key>Digest</key>
		<data>
		vGx4acKDmxw0BrFV4DJA/nAfbCI=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>BatteryLow0</key>
	<dict>
		<key>Digest</key>
		<data>
		RXpvw1UJ6LNmfeukx44vZNbUUdg=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>BatteryLow1</key>
	<dict>
		<key>Digest</key>
		<data>
		kWEGIIzsAMzWofwg48EuChsBy8Y=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>BatteryPlugin</key>
	<dict>
		<key>Digest</key>
		<data>
		x/UfRx+ZrvdD2hGJcsuDzTzbSEk=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>DeviceTree</key>
	<dict>
		<key>Digest</key>
		<data>
		MPqzXC8s1R6Ui6DZ6wsxNUxo2eE=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>KernelCache</key>
	<dict>
		<key>Digest</key>
		<data>
		oo0Gn116uhfkev7W+Mm7gpjh4mw=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>LLB</key>
	<dict>
		<key>BuildString</key>
		<string>iBoot-4513.270.14~26</string>
		<key>Digest</key>
		<data>
		LwQ2Fgqo3EaC3jTmzSZNkb7jc44=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>OS</key>
	<dict>
		<key>Digest</key>
		<data>
		mN9RizkYtLNbp0JL9vaWBw+Txb8=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>RecoveryMode</key>
	<dict>
		<key>Digest</key>
		<data>
		UbR/Y/NlxGA9d3FgfIqW3NqEBzs=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>RestoreDeviceTree</key>
	<dict>
		<key>Digest</key>
		<data>
		lE39qTAzIwfI7Hbdqu3+I7CutL0=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>RestoreKernelCache</key>
	<dict>
		<key>Digest</key>
		<data>
		plCjoduaE3baQWxizAt/R4zZYWw=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>RestoreLogo</key>
	<dict>
		<key>Digest</key>
		<data>
		9iKLUDAk4T848B/ZYdDZrjKt8VU=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>RestoreRamDisk</key>
	<dict>
		<key>Digest</key>
		<data>
		we40jsg+GT5iEHbBX8Rgx8lwnyE=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>RestoreSEP</key>
	<dict>
		<key>Digest</key>
		<data>
		nefBEisXw6m0AQeuuxecfqZ6+8M=
		</data>
		<key>Trusted</key>
		<true/>
		<key>ESEC</key>
		<true/>
		<key>EPRO</key>
		<true/>
	</dict>
	<key>RestoreTrustCache</key>
	<dict>
		<key>Digest</key>
		<data>
		D7mgr+103BiO70YeA8+gAFitR5Q=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>SEP</key>
	<dict>
		<key>Digest</key>
		<data>
		OpoMBkt9mhIKpOW58FNm0S30nls=
		</data>
		<key>Trusted</key>
		<true/>
		<key>ESEC</key>
		<true/>
		<key>EPRO</key>
		<true/>
	</dict>
	<key>StaticTrustCache</key>
	<dict>
		<key>Digest</key>
		<data>
		nVuzF2guRp8jW8TO0U08dxJhNvk=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>ftap</key>
	<dict>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
		<key>Digest</key>
		<data>
		</data>
	</dict>
	<key>ftsp</key>
	<dict>
		<key>Trusted</key>
		<true/>
		<key>ESEC</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>Digest</key>
		<data>
		</data>
	</dict>
	<key>iBEC</key>
	<dict>
		<key>BuildString</key>
		<string>iBoot-4513.270.14~26</string>
		<key>Digest</key>
		<data>
		0JvGpGdQ9K8+pkX2aspqKkZPSZw=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>iBSS</key>
	<dict>
		<key>BuildString</key>
		<string>iBoot-4513.270.14~26</string>
		<key>Digest</key>
		<data>
		i5HqOmFUikKw8bp5LGciR9f41EA=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>iBoot</key>
	<dict>
		<key>Digest</key>
		<data>
		8Xl+VGADZpieRXqABxTsaeIBm1o=
		</data>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
	</dict>
	<key>rfta</key>
	<dict>
		<key>Trusted</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>ESEC</key>
		<true/>
		<key>Digest</key>
		<data>
		</data>
	</dict>
	<key>rfts</key>
	<dict>
		<key>Trusted</key>
		<true/>
		<key>ESEC</key>
		<true/>
		<key>EPRO</key>
		<true/>
		<key>Digest</key>
		<data>
		</data>
	</dict>
	<key>ApNonce</key>
	<data>
	XjYxqysmRIWeBp2jfZKMcwEV4UQ=
	</data>
	<key>@ApImg4Ticket</key>
	<true/>
	<key>ApSecurityMode</key>
	<true/>
	<key>ApProductionMode</key>
	<true/>
	<key>SepNonce</key>
	<data>
	WTOSE1q/VyLTY6lonU1/IyZW7jM=
	</data>
</dict>
</plist>
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
common.c:printing 8233 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>@ServerVersion</key>
	<string>2.1.0</string>
	<key>ApImg4Ticket</key>
	<data>
	MIIWnBYESU00TQIBADGCDLT/hOqFnEKCDKswggynFgRNQU5CMYIMnf+E6oWcUIIBADCB
	/RYETUFOUDGB9P+EkrmGSB4wHBYEQk5DSAQUXjYxqysmRIWeBp2jfZKMcwEV4UT/hJK9
	pEQLMAkWBEJPUkQCAQb/hJqVoE8LMAkWBENFUE8CAQH/hJqhklAMMAoWBENISVACAnAA
	/4SawaRPCzAJFgRDUFJPAQH//4SazYpDCzAJFgRDU0VDAQH//4SqjZJEETAPFgRFQ0lE
	AgcWLFQ4Magm/4WakZ5NCzAJFgRTRE9NAgEB/4ebud5uHjAcFgRzbm9uBBRZM5ITWr9X
	ItNjqWidTX8jJlbuM/+Hm8nsbh4wHBYEc3J2bgQUNCrJQ8vDqDIv14eYY/N0elj+2RH/
	hpOF6DBlMGMWBGJhdDAxW/+Eop2mVB4wHBYEREdTVAQURXpvw1UJ6LNmfeukx44vZNbU
	Udj/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVT
	RUMBAf//hpOF6DFlMGMWBGJhdDExW/+Eop2mVB4wHBYEREdTVAQUkWEGIIzsAMzWofwg
	48EuChsBy8b/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikML
	MAkWBEVTRUMBAf//hpOF6EZlMGMWBGJhdEYxW/+Eop2mVB4wHBYEREdTVAQUvGx4acKD
	mxw0BrFV4DJA/nAfbCL/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//
	hKrNikMLMAkWBEVTRUMBAf//hpuhzjBlMGMWBGNoZzAxW/+Eop2mVB4wHBYEREdTVAQU
	tq8prikOt2WTaP7W27DVEA0KQ3//hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQ
	Uk8BAf//hKrNikMLMAkWBEVTRUMBAf//hpuhzjFlMGMWBGNoZzExW/+Eop2mVB4wHBYE
	REdTVAQUNbatNhLbMJ+JUUbBjLC9Jow7cNL/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8L
	MAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//hqPR5GVlMGMWBGR0cmUxW/+Eop2m
	VB4wHBYEREdTVAQUMPqzXC8s1R6Ui6DZ6wsxNUxo2eH/hKqtilkLMAkWBEVLRVkBAf//
	hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//hrPRwnBxMG8WBGZ0YXAx
	Z/+Eop2mVCowKBYEREdTVAQgU0C2oFm9tzLnFee7Gyku3NRcKo0dB+YDnT8zjXxEKKv/
	hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMB
	Af//hrPR5nBxMG8WBGZ0c3AxZ/+Eop2mVCowKBYEREdTVAQgU0C2oFm9tzLnFee7Gyku
	3NRcKo0dB+YDnT8zjXxEKKv/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8B
	Af//hKrNikMLMAkWBEVTRUMBAf//hrux8lBlMGMWBGdseVAxW/+Eop2mVB4wHBYEREdT
	VAQUx/UfRx+ZrvdD2hGJcsuDzTzbSEn/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkW
	BEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//hsuJymNlMGMWBGliZWMxW/+Eop2mVB4w
	HBYEREdTVAQU0JvGpGdQ9K8+pkX2aspqKkZPSZz/hKqtilkLMAkWBEVLRVkBAf//hKrB
	pE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//hsuJ3nRlMGMWBGlib3QxW/+E
	op2mVB4wHBYEREdTVAQU8Xl+VGADZpieRXqABxTsaeIBm1r/hKqtilkLMAkWBEVLRVkB
	Af//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//hsuJ5nNlMGMWBGli
	c3MxW/+Eop2mVB4wHBYEREdTVAQUi5HqOmFUikKw8bp5LGciR9f41ED/hKqtilkLMAkW
	BEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//hsux2GJl
	MGMWBGlsbGIxW/+Eop2mVB4wHBYEREdTVAQULwQ2Fgqo3EaC3jTmzSZNkb7jc47/hKqt
	ilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//
	htvJ3GxlMGMWBGtybmwxW/+Eop2mVB4wHBYEREdTVAQUoo0Gn116uhfkev7W+Mm7gpjh
	4mz/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVT
	RUMBAf//huO9zm9lMGMWBGxvZ28xW/+Eop2mVB4wHBYEREdTVAQUlKWyBoS/W2XT5kKt
	+BANOauEuvz/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikML
	MAkWBEVTRUMBAf//h5OR5mtlMGMWBHJkc2sxW/+Eop2mVB4wHBYEREdTVAQUwe40jsg+
	GT5iEHbBX8Rgx8lwnyH/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//
	hKrNikMLMAkWBEVTRUMBAf//h5OR6HJlMGMWBHJkdHIxW/+Eop2mVB4wHBYEREdTVAQU
	lE39qTAzIwfI7Hbdqu3+I7CutL3/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQ
	Uk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5OVxm1lMGMWBHJlY20xW/+Eop2mVB4wHBYE
	REdTVAQUUbR/Y/NlxGA9d3FgfIqW3NqEBzv/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8L
	MAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5OZ6GFxMG8WBHJmdGExZ/+Eop2m
	VCowKBYEREdTVAQgU0C2oFm9tzLnFee7Gyku3NRcKo0dB+YDnT8zjXxEKKv/hKqtilkL
	MAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5OZ
	6HNxMG8WBHJmdHMxZ/+Eop2mVCowKBYEREdTVAQgU0C2oFm9tzLnFee7Gyku3NRcKo0d
	B+YDnT8zjXxEKKv/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrN
	ikMLMAkWBEVTRUMBAf//h5Ot5G5lMGMWBHJrcm4xW/+Eop2mVB4wHBYEREdTVAQUplCj
	oduaE3baQWxizAt/R4zZYWz/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8B
	Af//hKrNikMLMAkWBEVTRUMBAf//h5Oxzm9lMGMWBHJsZ28xW/+Eop2mVB4wHBYEREdT
	VAQU9iKLUDAk4T848B/ZYdDZrjKt8VX/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkW
	BEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5O95mllMGMWBHJvc2kxW/+Eop2mVB4w
	HBYEREdTVAQUmN9RizkYtLNbp0JL9vaWBw+Txb//hKqtilkLMAkWBEVLRVkBAf//hKrB
	pE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5PNynBlMGMWBHJzZXAxW/+E
	op2mVB4wHBYEREdTVAQUnefBEisXw6m0AQeuuxecfqZ6+8P/hKqtilkLMAkWBEVLRVkB
	Af//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5PR5mNlMGMWBHJ0
	c2MxW/+Eop2mVB4wHBYEREdTVAQUD7mgr+103BiO70YeA8+gAFitR5T/hKqtilkLMAkW
	BEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//h5uV4Gll
	MGMWBHNlcGkxW/+Eop2mVB4wHBYEREdTVAQUOpoMBkt9mhIKpOW58FNm0S30nlv/hKqt
	ilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVTRUMBAf//
	h6PJ5nRlMGMWBHRyc3QxW/+Eop2mVB4wHBYEREdTVAQUnVuzF2guRp8jW8TO0U08dxJh
	Nvn/hKqtilkLMAkWBEVLRVkBAf//hKrBpE8LMAkWBEVQUk8BAf//hKrNikMLMAkWBEVT
	RUMBAf8EggEANveORxsTjfZb1VIZAI2yVDjpL00q/rRwfPDBx3fp6J5hk5gWW7QSzy/K
	bz59nm61q/1skkdsCtEVMAWIgEJyWI4iMgnnvcrcrugC/ZeTs01+KrivjmUxv5uCS1Tk
	aKOQYRu9QcwUe5xcoTa3khVGVrpIum2egDI6uc8/e6g/a2HsVjiVCCabOaGIn+HWw+BW
	KxpTukSbI05i3UeOm1dSHYRUtiVNy1qVzoAQu3FbkKFLRSf7sFSmT7U2fQcb5CatTnzN
	xfYnKz+ebG7QKADFfhHlvjj3NCd7V65eCXMM2yOKNYB5AM10defDxGa/Qmqshbab2Dy2
	JtteWPhbbGLxNDCCCNMwggP4MIIC4KADAgECAgEQMA0GCSqGSIb3DQEBBQUAMGIxCzAJ
	BgNVBAYTAlVTMRMwEQYDVQQKEwpBcHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0
	aWZpY2F0aW9uIEF1dGhvcml0eTEWMBQGA1UEAxMNQXBwbGUgUm9vdCBDQTAeFw0wNzAx
	MDUxOTIxNTlaFw0yMjAxMDUxOTIxNTlaMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQKEwpB
	cHBsZSBJbmMuMSYwJAYDVQQLEx1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEy
	MDAGA1UEAxMpQXBwbGUgU2VjdXJlIEJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw
	ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD+8t3aZTmwcuMDhIH0VsnRoUq7
	yAQB80YNleE3lQppR8bEjHk+R1UGsgYU636k9SP+QjWY7zQFzprTrZTQog/C0rQESEwj
	WlvHC51i0/PjaxD+lwhXxhJ2dxmyxsMsmO23KYfk3Bi25fO6E/uytrdn2cvfb6WTPe16
	k2e0/TQW5ACrC7dOH1rWA2g+crYUMDoMZJegRiJ5G3csWy6Q4BHcFqPhyPeEsk/cSzoK
	1RJ+3BE/+hFzZRpJcKB+dYK0PCsvVd8wiLF1TUXcBygtSjqF/Z+VPiK6nEb3t2h7s5TV
	Qj4Fszj4Z3lIjGwfi77u7VQF1aMLWH14DySpodwKdOr3AgMBAAGjgZwwgZkwDgYDVR0P
	AQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFEk9NlPJ1xXhhmFOrKur
	GFZjXcPGMB8GA1UdIwQYMBaAFCvQaUeUdgn+9GuNLkCm90dNfwheMDYGA1UdHwQvMC0w
	K6ApoCeGJWh0dHA6Ly93d3cuYXBwbGUuY29tL2FwcGxlY2Evcm9vdC5jcmwwDQYJKoZI
	hvcNAQEFBQADggEBADTFDMUOWREvpsKfMnjnZDJp263CJcq3R4O3kjxxU6CyrTCVgFC9
	bV9M3M54DUxJEFA4EDW/RYGsZlgsISP4ll6A6dPGTP2Frjlh9iiqRO0Vmz9HwFesZxyM
	zdSTjU/balSne0JbD5nG1zirUqehgx2FMHTqDR3aaISP4oR+y7lBbtWfqEK1/zO2cX/q
	o7ndSQNghXYQPo6o4TbjEt2FbO1mU7BbSJsvf/bKHPBdmC10rfBIR8XhmmeyIg+wDgKg
	4bpqYrm0tXH0JeGz5aDtyBpAtfgxFQWkXDgjTJCdRwOAgNQykEWPD6+b/ALu7cvmMfaf
	FeZ9K1dDDuIPoaCtidowggTTMIIDu6ADAgECAgICBzANBgkqhkiG9w0BAQUFADB+MQsw
	CQYDVQQGEwJVUzETMBEGA1UEChMKQXBwbGUgSW5jLjEmMCQGA1UECxMdQXBwbGUgQ2Vy
	dGlmaWNhdGlvbiBBdXRob3JpdHkxMjAwBgNVBAMTKUFwcGxlIFNlY3VyZSBCb290IENl
	cnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTEyMTIxNDAxNTkyOVoXDTIyMTIxNTAxNTky
	OVowZDELMAkGA1UEBhMCVVMxEzARBgNVBAoTCkFwcGxlIEluYy4xDDAKBgNVBAsTA0VU
	UzEyMDAGA1UEAxMpVDcwMDAtVHNzTGl2ZS1NYW5pZmVzdEtleS1SZXZBLURhdGFDZW50
	ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvrQAPzww+GoteXt7BUonr
	C3boehKn6kK3suU8DZ62jsixX0U0GBAzYoYBnIPy1skMb7Wc5Pm8P+dPdhCXEq8ssScR
	ErPlxsb7Pnr5Z/dz3cKTDkOIL7ZFs23VXiGMv8b6QVpjHHox2BY+3yNVVWvvG9UIHodo
	gNsR5uxAgNWTL/8p0WuZd/Q6Msvsi2quCTay4oRaJHgh/y075EXaOtmFqHEeGpp8ETPV
	SLj3om035ccJnVtjZMvSRr3nPWlp1DGpDqZJChGBVSh0KxF+W6RKgNRBKM41uQO595TL
	fI6jeOLAXiC68BLnck88bZCXJKzGL9K4eKffND71CxT0kw3LAgMBAAGjggFzMIIBbzAL
	BgNVHQ8EBAMCB4AwHQYDVR0OBBYEFPLj4fsIIG3bdu7+4RmKvT39yIjMMB8GA1UdIwQY
	MBaAFEk9NlPJ1xXhhmFOrKurGFZjXcPGMIIBHgYKKoZIhvdjZAYBDwEB/wSCAQsxggEH
	/4TqhZxQgbUwgbIWBE1BTlAxgan/hJK5hkgMMAoWBEJOQ0igAgUA/4SSvaREDDAKFgRC
	T1JEoAIFAP+EmpWgTwswCRYEQ0VQTwIBAf+EmqGSUAwwChYEQ0hJUAICcAD/hJrBpE8M
	MAoWBENQUk+gAgUA/4SazYpDDDAKFgRDU0VDoAIFAP+Eqo2SRAwwChYERUNJRKACBQD/
	hZqRnk0LMAkWBFNET00CAQH/h5u53m4MMAoWBHNub26gAgUA/4T6iZRQQzBBFgRPQkpQ
	MTn/hKKdplQMMAoWBERHU1SgAgUA/4SqwaRPDDAKFgRFUFJPoAIFAP+Eqs2KQwwwChYE
	RVNFQ6ACBQAwDQYJKoZIhvcNAQEFBQADggEBAAM64EB29n6J1sUd/GRReKRTMQoVTB7L
	Fi8C0jEiRIV3yv94gDKq+1M6Y+lxGWdEiTxG7VmdgBuRyudyAmhlttcfXYKcpw9mJehs
	XbZBgg9oEo+c3aohqwYWoZ8pOxUeQtMfNNUGN+bSw9TYqHBx7ni05K3Cz6ntS2QjJgP3
	IZTSYhySVppNSDHvyxH+fr35wpsou7V6OM+gBb4hXkiFNknAOfUx6D6Vc7zSXQahyooT
	GU0T1560HuL+R6Po9SrYmiRrAXrr0RDqLZgZ7QPk6+1Ql/9JKRplOsxzRp8vR9FmKhRH
	+5RV9/Z8pXuWpNESjGmJIXmx+InZ1EHqHpCSO3E=
	</data>
</dict>
</plist>
Received SHSH blobs
DEBUG: tss_response_get_path_by_entry: No entry 'iBEC' in TSS response
NOTE: No path for component iBEC in TSS, will fetch from build_identity
Extracting iBEC.n61.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Tag found
Sending iBEC (731534 bytes)...
Waiting for device to disconnect...
irecv_event_cb: device 00162c543831a826 (udid: N/A) disconnected
Waiting for device to reconnect in recovery mode...
irecv_event_cb: device 00162c543831a826 (udid: N/A) connected in Recovery mode
opening device 05ac:1281...
found device with ECID 00162c543831a826
Setting to configuration 1
Setting to interface 0:0
Recovery Mode Environment:
iBoot build-version=iBoot-4513.270.14
iBoot build-style=RELEASE
Sending RestoreLogo...
DEBUG: tss_response_get_path_by_entry: No entry 'RestoreLogo' in TSS response
NOTE: No path for component RestoreLogo in TSS, will fetch from build_identity
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Tag found
Sending RestoreLogo (12334 bytes)...
DEBUG: RestoreTrustCache is loaded by iBoot.
DEBUG: tss_response_get_path_by_entry: No entry 'RestoreTrustCache' in TSS response
NOTE: No path for component RestoreTrustCache in TSS, will fetch from build_identity
Extracting 038-53416-004.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Tag found
Sending RestoreTrustCache (9813 bytes)...
ramdisk-size=0x10000000
DEBUG: tss_response_get_path_by_entry: No entry 'RestoreRamDisk' in TSS response
NOTE: No path for component RestoreRamDisk in TSS, will fetch from build_identity
Extracting 038-53416-004.dmg...
Personalizing IMG4 component RestoreRamDisk...
Tag found
Sending RestoreRamDisk (93852363 bytes)...
DEBUG: tss_response_get_path_by_entry: No entry 'RestoreDeviceTree' in TSS response
NOTE: No path for component RestoreDeviceTree in TSS, will fetch from build_identity
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Tag found
Sending RestoreDeviceTree (125714 bytes)...
DEBUG: tss_response_get_path_by_entry: No entry 'RestoreKernelCache' in TSS response
NOTE: No path for component RestoreKernelCache in TSS, will fetch from build_identity
Extracting kernelcache.release.iphone7...
Personalizing IMG4 component RestoreKernelCache...
Tag found
Sending RestoreKernelCache (14067184 bytes)...
DEBUG: Waiting for device to disconnect...
irecv_event_cb: device 00162c543831a826 (udid: N/A) disconnected
Waiting for device to enter restore mode...
idevice_event_cb: device 00162c543831a826 (udid: dde0ac13d3e811b8273a6774f557143d93c81a77) connected in restore mode
About to restore device... 
restore_is_current_device: Connected to com.apple.mobile.restored, version 15
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device dde0ac13d3e811b8273a6774f557143d93c81a77 has successfully entered restore mode
Hardware Information:
BoardID: 6
ChipID: 28672
UniqueChipID: 6241189719287846
ProductionMode: true
Previous restore exit status: 0x100
Starting FDR listener thread
Connecting to FDR client at port 1082
About to do ctrl handshake
FDR sending 89 bytes:
common.c:printing 287 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>BeginCtrl</string>
	<key>CtrlProtoVersion</key>
	<integer>2</integer>
</dict>
</plist>
FDR Sent 89 bytes
FDR Received 105 bytes
common.c:printing 334 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>BeginCtrl</string>
	<key>CtrlProtoVersion</key>
	<integer>2</integer>
	<key>ConnPort</key>
	<integer>49159</integer>
</dict>
</plist>
Ctrl handshake done (ConnPort = 49159)
FDR 0x561a4ad9bf10 waiting for message...
TZ0RequiredCapacity: 0xC00000
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
About to send NORData...
DEBUG: tss_response_get_path_by_entry: No entry 'LLB' in TSS response
NOTE: Could not get LLB path from TSS data, will fetch from build identity
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.n61.RELEASE.im4p...
Personalizing IMG4 component LLB...
Tag found
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Tag found
Extracting batterycharging0@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Tag found
Extracting batterycharging1@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Tag found
Extracting batteryfull@2x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Tag found
Extracting batterylow0@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Tag found
Extracting batterylow1@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Tag found
Extracting glyphplugin@1334~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Tag found
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component DeviceTree...
Tag found
Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Tag found
Extracting iBoot.n61.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Tag found
Extracting sep-firmware.n61.RELEASE.im4p...
Personalizing IMG4 component RestoreSEP...
Tag found
Extracting sep-firmware.n61.RELEASE.im4p...
Personalizing IMG4 component SEP...
Tag found
common.c:supressed printing 9914630 bytes plist...
Sending NORData now...
Done sending NORData
ERROR: Could not read data (-256). Aborting.
idevice_event_cb: device 00162c543831a826 (udid: dde0ac13d3e811b8273a6774f557143d93c81a77) disconnected
irecv_event_cb: device 00162c543831a826 (udid: dde0ac13d3e811b8273a6774f557143d93c81a77) connected in Recovery mode
FDR 0x561a4ad9bf10 terminating...
ERROR: Unable to restore device

**Comment by TheNegativeZero** [comment]
[errorlog.txt](https://github.com/libimobiledevice/idevicerestore/files/4720840/errorlog.txt)
much clearer.

**Comment by TheNegativeZero** [comment]
[Summary Log.txt](https://github.com/libimobiledevice/idevicerestore/files/4721048/Summary.Log.txt)

**Comment by TheNegativeZero** [comment]
Hi Nikias, did you receive the idevicerestore logs that you requested?
Any hint about how to make this work is greatly appreciated.  Thanks in advance.

**Comment by TheNegativeZero** [comment]
Hi @nikias , did you receive the idevicerestore logs that you requested?
Any hint about how to make this work is greatly appreciated. I took a look at all libraries upstream but cannot pinpoint the error as everything compiles ok.
I will continue crunching code but it would be very helpful to hear from you ideas as to where to look for this bug.
Thanks in advance.

**Comment by nikias** [comment]
@TheNegativeZero I get every single message on any of these issues. It looks like the connection just fails (after sending the NORData). Have you made sure that you are using the latest code for all the depending libs? libirecovery, libplist, libusbmuxd, and libimobiledevice?

**Comment by TheNegativeZero** [comment]
Hi @nikias, I know you are very busy and I dont want to take too much time from you.  
Summary: iPhone 6, Ubuntu 20.04, 4 different USB cables.  Increased timeout, printed checkpoints (below, with --).  FDR fails.  Everything points at something upstream (libimobiledevice, libusbmuxd, etc.) but cannot put my finger on it.

Sending NORData now...
Done sending NORData
Could not read data (-256). Aborting.
--   FDR: 0x5650650e74b0 
--   Device Error: -2 
--   IDEVICE_E_TIMEOUT: -7 
--   IDEVICE_E_SUCCESS: 0 
--   cmd: 32589 
--   sizeof(cmd): 2 
--   bytes: 0
ERROR: Unable to restore device

In every complite I GIT CLONE libirecovery, idevicerestore, usbmuxd, libimobiledevice, libusbmuxd, libplist.  Also installed/updated libcurl4-openssl-dev libplist-dev libzip-dev openssl libssl-dev libusb-1.0-0-dev libreadline-dev build-essential git make automake libtool pkg-config ifuse (some are old and do not install).

Seems pretty straight forward and I have done this before flawlessly.  Dont know why it does not work now.

Thanks in advance.  Appreciated.

**Comment by yogendra123456** [comment]
Hi All,

i try to restore my device but it create error again and again on windows 10... i am using libmobiledevice code.

Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.n71.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Extracting sep-firmware.n71.RELEASE.im4p...
Personalizing IMG4 component RestoreSEP...
Extracting sep-firmware.n71.RELEASE.im4p...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checking filesystems (15)
ERROR: Unable to receive message from FDR 00000124E29C2130 (-7). 0/2 bytes

Details in attached file..
[ErrorRelease.txt](https://github.com/libimobiledevice/idevicerestore/files/4757500/ErrorRelease.txt)


kindly provide the update what is the solution of this error, i am using latest libmobiledevice code with visual studio 2019...

thanks in advanced....

**Comment by yogendra123456** [comment]
Hi @TheNegativeZero ,

thanks for concern, if you work on windows and find any solution then mail me...

**Comment by TheNegativeZero** [comment]
hi @nikias, after several recompiles I have learned a few things but the problem persists:

1. I have gitcloned and recompiled all 5 libraries in addition to idevicerestore.  All libs were generated on /usr/local/lib while idevicerestore is on /usr/local/bin.  LDD idevicerestore checks out.

2. installed/updated every single library dependency.  ==> running Ubuntu 20.04

3. Added checkpoints to trace the error message in the code for fdr.c and restore.c in idevicerestore.  Also increased connection retries and sleep (wait) times.

4. Run usbmuxd -f -v -v to track down the moment idevicerestore fails.  Found out that usbmuxd shows an error -71 before shutting down the connection.  I read somewhere that this is caused by a timeout waiting for an ack from the phone:

[45.784566] [00022f43] libusb: debug [libusb_free_transfer] transfer 0x564f488fe020
[45.784604] [00022f43] libusb: debug [reap_for_handle] urb type=3 status=-71 transferred=0
[45.784633] [00022f43] libusb: debug [handle_bulk_completion] handling completion status -71 of bulk urb 1/1
[45.784662] [00022f43] libusb: debug [handle_bulk_completion] low level error -71
[45.784688] [00022f43] libusb: debug [usbi_handle_transfer_completion] transfer 0x564f48921860 has callback 0x564f469788b0
[14:28:24.099][4] Device 1-18 RX aborted due to error or disconnect

5. Irecovery works well and idevicerestore runs well until it hits the error.  If just out of fun I run idevicerestore -l -x, the program runs to completion, obviously without copying any firmware.

6. This info leads me to believe that somehow the bulk transfer between Linux (idevicerestore and libs) and the iPhone screws up, maybe at the libusbmuxd level?  I am looking for ways to test this connection without using idevicerestore.  What puzzles me is that I am using the latest libusbmuxd and usbmuxd libs as published on this git.

I have tested with original Apple cable, different usb ports, different laptop (Ubuntu 18.04).
I have run out of ideas.  --Thanks.

**Comment by TheNegativeZero** [comment]
Closing this unresolved issue as no solution is on sight.

**Comment by nikias** [comment]
I wouldn't give up on this. @MrSaatci what error situations are you confronted with?

**Comment by MrSaatci** [comment]
It is weird, I randomly fail at either entering restore mode (which goes into recovery instead) or I get the FDR error.

Sending RestoreDeviceTree (125714 bytes)...
DEBUG: tss_response_get_path_by_entry: No entry 'RestoreKernelCache' in TSS response
NOTE: No path for component RestoreKernelCache in TSS, will fetch from build_identity
Extracting kernelcache.release.iphone7...
Personalizing IMG4 component RestoreKernelCache...
Tag found
Sending RestoreKernelCache (14069209 bytes)...
DEBUG: Waiting for device to disconnect...
irecv_event_cb: device 001d595218f94f26 (udid: N/A) disconnected
Waiting for device to enter restore mode...
irecv_event_cb: device 001d595218f94f26 (udid: N/A) connected in Recovery mode
ERROR: Device failed to enter restore mode.




FDR

FDR Sent 89 bytes
FDR Received 105 bytes
common.c:printing 334 bytes plist:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Command</key>
	<string>BeginCtrl</string>
	<key>CtrlProtoVersion</key>
	<integer>2</integer>
	<key>ConnPort</key>
	<integer>49159</integer>
</dict>
</plist>
Ctrl handshake done (ConnPort = 49159)
TZ0RequiredCapacity: 0xC00000
FDR 0x55a8dc46ed30 waiting for message...
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
ERROR: Could not read data (-256). Aborting.
ERROR: Unable to receive message from FDR 0x55a8dc46ed30 (-2). 0/2 bytes
FDR 0x55a8dc46ed30 terminating...
ERROR: Unable to restore device
idevice_event_cb: device 001d595218f94f26 (udid: ffffffffffffffffffffffffffffffff00000001) disconnected
eden@eden-ubuntu:~$ sudo idevicerestore -
